/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fatec.aula;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author 0040481722011
 */
public class EstatisticaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form EstatisticaJFrame
     */
    public EstatisticaJFrame() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        XYButton = new javax.swing.JButton();
        pizzaButton = new javax.swing.JButton();
        scatterplotButton = new javax.swing.JButton();
        barra2dButton = new javax.swing.JButton();
        barra3dButton = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        numeroTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        numerosList = new javax.swing.JList<>();
        excluirButton = new javax.swing.JButton();
        limparButton = new javax.swing.JButton();
        graphicsPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        mediaTextField = new javax.swing.JTextField();
        mediaLabel = new javax.swing.JLabel();
        medianaLabel = new javax.swing.JLabel();
        medianaTextField = new javax.swing.JTextField();
        calcButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        modaLabel = new javax.swing.JLabel();
        modaTextField = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gráficos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(99, 110, 114));

        jPanel2.setLayout(new java.awt.GridLayout(1, 8, 10, 2));

        XYButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        XYButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/icons/chart-2-64.png"))); // NOI18N
        XYButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XYButtonActionPerformed(evt);
            }
        });
        jPanel2.add(XYButton);

        pizzaButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pizzaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/icons/pie-chart-3-64.png"))); // NOI18N
        pizzaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaButtonActionPerformed(evt);
            }
        });
        jPanel2.add(pizzaButton);

        scatterplotButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        scatterplotButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/icons/scatter-plot-64.png"))); // NOI18N
        scatterplotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scatterplotButtonActionPerformed(evt);
            }
        });
        jPanel2.add(scatterplotButton);

        barra2dButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        barra2dButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/icons/bar-chart-5-64.png"))); // NOI18N
        barra2dButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra2dButtonActionPerformed(evt);
            }
        });
        jPanel2.add(barra2dButton);

        barra3dButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        barra3dButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/icons/bar-chart-2-64.png"))); // NOI18N
        barra3dButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra3dButtonActionPerformed(evt);
            }
        });
        jPanel2.add(barra3dButton);

        jButton9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton9.setText("Desvio");
        jPanel2.add(jButton9);

        numeroTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        numeroTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTextFieldActionPerformed(evt);
            }
        });
        numeroTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numeroTextFieldKeyPressed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(76, 209, 55));
        addButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/icons/add-24.png"))); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        numerosList.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jScrollPane1.setViewportView(numerosList);

        excluirButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        excluirButton.setText("Excluir");
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirButtonActionPerformed(evt);
            }
        });

        limparButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(numeroTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(limparButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(excluirButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(excluirButton)
                .addGap(7, 7, 7)
                .addComponent(limparButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout graphicsPanelLayout = new javax.swing.GroupLayout(graphicsPanel);
        graphicsPanel.setLayout(graphicsPanelLayout);
        graphicsPanelLayout.setHorizontalGroup(
            graphicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        graphicsPanelLayout.setVerticalGroup(
            graphicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(200, 214, 229));

        mediaTextField.setEditable(false);
        mediaTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        mediaLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mediaLabel.setText("Média");

        medianaLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        medianaLabel.setText("Mediana");

        medianaTextField.setEditable(false);
        medianaTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        calcButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        calcButton.setText("Calcular");
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        modaLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        modaLabel.setText("Moda");

        modaTextField.setEditable(false);
        modaTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jTextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Salvar Gráfico como:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mediaTextField)
                    .addComponent(mediaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medianaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medianaLabel))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(modaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(modaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mediaLabel)
                    .addComponent(medianaLabel)
                    .addComponent(modaLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mediaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(medianaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(saveButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(graphicsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graphicsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private DefaultListModel model = new DefaultListModel();

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        try {
            String texto = numeroTextField.getText().replace(",", ".");

            Double num = Double.parseDouble(texto);

            numerosList.setModel(model);
            model.addElement(num);
            numeroTextField.setText("");

            media += num;
            
            

        } catch (Exception E) {

            JOptionPane.showMessageDialog(null,
                    "Favor inserir Número", // MENSAGEM
                    "Erro", // TITULO
                    JOptionPane.WARNING_MESSAGE); //ICONE
        }


    }//GEN-LAST:event_addButtonActionPerformed

    private void limparButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparButtonActionPerformed

        model.clear();

        mediaTextField.setText("");
        media = 0.0;

        numerosList.setModel(model);
    }//GEN-LAST:event_limparButtonActionPerformed

    private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirButtonActionPerformed

        try {
            int index = numerosList.getSelectedIndex();
            model.remove(index);
            numerosList.setModel(model);
            numeroTextField.setText("");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null,
                    "Selecione um dado", // MENSAGEM
                    "Erro", // TITULO
                    JOptionPane.WARNING_MESSAGE); //ICONE
        }

    }//GEN-LAST:event_excluirButtonActionPerformed

    private void XYButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XYButtonActionPerformed

        teste = 1;
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (int i = 0; i < model.getSize(); i++) {
            String numStr = String.valueOf(model.get(i));
            Double num = Double.parseDouble(numStr);
            dataset.addValue(num, "Numero", "" + (i + 1));
        }

        xy = ChartFactory.createLineChart("XY",
                "Índices",
                "Valores",
                dataset,
                PlotOrientation.VERTICAL,
                true,
                true,
                false);

        // PARTE PADRÃO DE TODOS OS GRÁFICOS 
        ChartPanel panel = new ChartPanel(xy);
        int width = graphicsPanel.getWidth();
        int height = graphicsPanel.getHeight();

        panel.setPreferredSize(new Dimension(width, height));

        graphicsPanel.setLayout(new BorderLayout());
        graphicsPanel.add(panel, BorderLayout.CENTER);
        graphicsPanel.validate();


    }//GEN-LAST:event_XYButtonActionPerformed

    private void numeroTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroTextFieldKeyPressed

        int key = evt.getKeyCode();

        if (key == KeyEvent.VK_ENTER) {
            addButton.doClick();
        }
    }//GEN-LAST:event_numeroTextFieldKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        numeroTextField.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void pizzaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaButtonActionPerformed

        teste = 2;
        DefaultPieDataset dataset = new DefaultPieDataset();

        for (int i = 0; i < model.getSize(); i++) {
            String numStr = String.valueOf(model.get(i));
            Double num = Double.parseDouble(numStr);
            dataset.setValue("" + (i + 1), num);
        }

         pie = ChartFactory.createPieChart("Pizza",
                dataset,
                true,
                true,
                false);

        // PARTE PADRÃO DE TODOS OS GRÁFICOS 
        ChartPanel panel = new ChartPanel(pie);
        int width = graphicsPanel.getWidth();
        int height = graphicsPanel.getHeight();

        panel.setPreferredSize(new Dimension(width, height));

        graphicsPanel.setLayout(new BorderLayout());
        graphicsPanel.add(panel, BorderLayout.CENTER);
        graphicsPanel.validate();


    }//GEN-LAST:event_pizzaButtonActionPerformed

    private void scatterplotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scatterplotButtonActionPerformed

        teste = 3;
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        XYSeriesCollection resultado = new XYSeriesCollection();
        XYSeries series = new XYSeries("A");

        for (int i = 0; i < model.getSize(); i++) {
            String numStr = String.valueOf(model.get(i));
            Double num = Double.parseDouble(numStr);
            dataset.addValue(num, "Numero", "" + (i + 1));

            series.add(i, num);
        }
        resultado.addSeries(series);
          sp = ChartFactory.createScatterPlot("Scatter Plot",
                "X",
                "Y",
                resultado,
                PlotOrientation.VERTICAL,
                true,
                true,
                false);

        // PARTE PADRÃO DE TODOS OS GRÁFICOS 
        ChartPanel panel = new ChartPanel(sp);
        int width = graphicsPanel.getWidth();
        int height = graphicsPanel.getHeight();

        panel.setPreferredSize(new Dimension(width, height));

        graphicsPanel.setLayout(new BorderLayout());
        graphicsPanel.add(panel, BorderLayout.CENTER);
        graphicsPanel.validate();

    
    }//GEN-LAST:event_scatterplotButtonActionPerformed

    private void barra2dButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra2dButtonActionPerformed

        teste = 4;
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (int i = 0; i < model.getSize(); i++) {
            String numStr = String.valueOf(model.get(i));
            Double num = Double.parseDouble(numStr);
            dataset.addValue(num, "Numero", "" + (i + 1));
        }

         bar2d = ChartFactory.createBarChart("2D Bar",
                "Índices",
                "Valores",
                dataset,
                PlotOrientation.VERTICAL,
                true,
                true,
                false);

        // PARTE PADRÃO DE TODOS OS GRÁFICOS 
        ChartPanel panel = new ChartPanel(bar2d);
        int width = graphicsPanel.getWidth();
        int height = graphicsPanel.getHeight();

        panel.setPreferredSize(new Dimension(width, height));

        graphicsPanel.setLayout(new BorderLayout());
        graphicsPanel.add(panel, BorderLayout.CENTER);
        graphicsPanel.validate();

  
    }//GEN-LAST:event_barra2dButtonActionPerformed

    private void barra3dButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra3dButtonActionPerformed

        teste = 5;
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (int i = 0; i < model.getSize(); i++) {
            String numStr = String.valueOf(model.get(i));
            Double num = Double.parseDouble(numStr);
            dataset.addValue(num, "Numero", "" + (i + 1));
        }

        dataset.addValue(20, "Indice", "20");

         bar3d = ChartFactory.createBarChart3D("3D Bar",
                "Índices",
                "Valores",
                dataset,
                PlotOrientation.VERTICAL,
                true,
                true,
                false);

        // PARTE PADRÃO DE TODOS OS GRÁFICOS 
        ChartPanel panel = new ChartPanel(bar3d);
        int width = graphicsPanel.getWidth();
        int height = graphicsPanel.getHeight();

        panel.setPreferredSize(new Dimension(width, height));

        graphicsPanel.setLayout(new BorderLayout());
        graphicsPanel.add(panel, BorderLayout.CENTER);
        graphicsPanel.validate();

    }//GEN-LAST:event_barra3dButtonActionPerformed

    private void numeroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroTextFieldActionPerformed

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        // TODO add your handling code here:

        try {

            media /= model.getSize();

            mediaTextField.setText(String.valueOf(String.format(" %.2f", media)));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Sem valores", "Valor", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_calcButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:

            File save = new File(jTextField1.getText() + ".jpeg");

            switch (teste) {
                case 1:
                    if (!save.exists()) {
                        try {
                            ChartUtilities.saveChartAsJPEG(save, xy, 400, 600);
                        } catch (IOException ex) {
                            Logger.getLogger(EstatisticaJFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    break;

                case 2:
                    if (!save.exists()) {
                        try {
                            ChartUtilities.saveChartAsJPEG(save, pie, 400, 600);
                        } catch (IOException ex) {
                            Logger.getLogger(EstatisticaJFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    break;
                    
                    case 3:
                    if (!save.exists()) {
                        try {
                            ChartUtilities.saveChartAsJPEG(save, sp, 400, 600);
                        } catch (IOException ex) {
                            Logger.getLogger(EstatisticaJFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    break;
                    
                    case 4:
                    if (!save.exists()) {
                        try {
                            ChartUtilities.saveChartAsJPEG(save, bar2d, 400, 600);
                        } catch (IOException ex) {
                            Logger.getLogger(EstatisticaJFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    break;
                    
                    case 5:
                    if (!save.exists()) {
                        try {
                            ChartUtilities.saveChartAsJPEG(save, bar3d, 400, 600);
                        } catch (IOException ex) {
                            Logger.getLogger(EstatisticaJFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    break;
            }

            JOptionPane.showMessageDialog(null, "Gráfico salvo com sucesso!", "Sucesso!", JOptionPane.OK_OPTION);
        

    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstatisticaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstatisticaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstatisticaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstatisticaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstatisticaJFrame().setVisible(true);
            }
        });
    }




    private double media = 0;
    public JFreeChart xy;
    public JFreeChart sp;
    public JFreeChart pie;
    public JFreeChart bar2d;
    public JFreeChart bar3d;
    private int teste = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton XYButton;
    private javax.swing.JButton addButton;
    private javax.swing.JButton barra2dButton;
    private javax.swing.JButton barra3dButton;
    private javax.swing.JButton calcButton;
    private javax.swing.JButton excluirButton;
    private javax.swing.JPanel graphicsPanel;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton limparButton;
    private javax.swing.JLabel mediaLabel;
    private javax.swing.JTextField mediaTextField;
    private javax.swing.JLabel medianaLabel;
    private javax.swing.JTextField medianaTextField;
    private javax.swing.JLabel modaLabel;
    private javax.swing.JTextField modaTextField;
    private javax.swing.JTextField numeroTextField;
    private javax.swing.JList<String> numerosList;
    private javax.swing.JButton pizzaButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton scatterplotButton;
    // End of variables declaration//GEN-END:variables


    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("statistics-24.png")));
    }
}
